@echo off
setlocal enabledelayedexpansion

echo ============================================
echo  OpenBCI GUI - Build Script (VEP/AEP modded)
echo ============================================

set SKETCH_DIR=E:\deskbook\OpenBCI_GUI
set PROC_DIR=C:\Program Files\Processing\app
set JAVA=%PROC_DIR%\resources\jdk\bin\java.exe
set JAVAC=%PROC_DIR%\resources\jdk\bin\javac.exe

echo [1/4] Copying libraries...
if not exist "%SKETCH_DIR%\build_tools" mkdir "%SKETCH_DIR%\build_tools" 2>nul
copy /Y "%PROC_DIR%\resources\core\library\core-4.5.2.jar" "%SKETCH_DIR%\build_tools\" >nul
copy /Y "%PROC_DIR%\gluegen-rt-2.6.0-*.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
copy /Y "%PROC_DIR%\jogl-all-2.6.0-*.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
copy /Y "%PROC_DIR%\*windows-amd64*.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
copy /Y "%PROC_DIR%\resources\modes\java\libraries\serial\library\*.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
copy /Y "%PROC_DIR%\resources\modes\java\libraries\net\library\net.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
copy /Y "%PROC_DIR%\resources\modes\java\libraries\io\library\io.jar" "%SKETCH_DIR%\build_tools\" >nul 2>nul
echo [1/4] Done.

echo [2/4] Preprocessing sketch...
if exist "%SKETCH_DIR%\build" rmdir /S /Q "%SKETCH_DIR%\build"

REM Use Java classpath wildcards (*) to avoid 8191-char cmd limit.
REM Java expands dir\* internally, not at the shell level.
set MY_CP=%PROC_DIR%\resources\core\library\*;%PROC_DIR%\*;%PROC_DIR%\resources\modes\java\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\minim\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\controlP5\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\grafica\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\brainflow\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\httprequests_processing\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\oscP5\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\udp\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\openbci_gui_helpers\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\libraries\jSerialComm\library\*
set MY_CP=!MY_CP!;%SKETCH_DIR%\code\LSLLink.jar

"%JAVA%" -cp "!MY_CP!" processing.mode.java.Commander --sketch="%SKETCH_DIR%" --output="%SKETCH_DIR%\build" --force --build 2>nul

if exist "%SKETCH_DIR%\build\source\OpenBCI_GUI.java" (
    echo [2/4] Done.
) else (
    echo.
    echo ERROR: Preprocessing failed - no Java file generated.
    echo Try running "build.bat" from a Windows command prompt as administrator.
    pause
    exit /b 1
)

echo [3/4] Cleaning imports...
set JAVA_FILE=%SKETCH_DIR%\build\source\OpenBCI_GUI.java
set CLEAN_FILE=%SKETCH_DIR%\build\source\_temp_clean.java

powershell -NoProfile -Command "$f='%SKETCH_DIR%\build\source\OpenBCI_GUI.java'; $l=select-string -Pattern 'import ddf\.minim' -Path $f | select -First 1; if ($l) { $s=$l.LineNumber } else { $s=-1 }; if ($s -gt 0) { $all = [System.IO.File]::ReadAllLines($f); $h='/* autogenerated by Processing */'; $new=@($h,'import processing.core.*;','import processing.data.*;','import processing.event.*;','import processing.opengl.*;','import java.awt.Graphics;','import java.util.Date;','import java.awt.event.KeyEvent;'); $new += $all[($s-1)..($all.Length-1)]; [System.IO.File]::WriteAllLines('%CLEAN_FILE%',$new); exit 0 } else { exit 1 }"
if %ERRORLEVEL% NEQ 0 goto compile_fail
if exist "%CLEAN_FILE%" (
    move /Y "%CLEAN_FILE%" "%JAVA_FILE%" >nul
) else (
    goto compile_fail
)
echo [3/4] Done.

echo [4/4a] Extracting native DLLs...
if not exist "%SKETCH_DIR%\build\natives" mkdir "%SKETCH_DIR%\build\natives" 2>nul

REM Extract native DLLs from JOGL/gluegen native jars
cd "%SKETCH_DIR%\build\natives"
for %%j in ("%PROC_DIR%\gluegen-rt-*-natives-windows-amd64-*.jar") do (
    "%PROC_DIR%\resources\jdk\bin\jar.exe" xf "%%j" 2>nul
)
for %%j in ("%PROC_DIR%\jogl-all-*-natives-windows-amd64-*.jar") do (
    "%PROC_DIR%\resources\jdk\bin\jar.exe" xf "%%j" 2>nul
)
cd "%SKETCH_DIR%"

REM Move DLLs from subdirs to root
for /R "%SKETCH_DIR%\build\natives" %%d in (*.dll) do (
    if not "%%~dpd"=="%SKETCH_DIR%\build\natives\" move /Y "%%d" "%SKETCH_DIR%\build\natives\" 2>nul
)
for /d %%d in ("%SKETCH_DIR%\build\natives\*") do rmdir /S /Q "%%d" 2>nul
del "%SKETCH_DIR%\build\natives\*.class" 2>nul 2>nul

echo DLLs found:
dir /B "%SKETCH_DIR%\build\natives\*.dll" 2>nul
if not exist "%SKETCH_DIR%\build\natives\*.dll" (
    echo WARNING: No native DLLs extracted. Attempting alternate extraction...
    REM Try using PowerShell to unzip directly
    for %%j in ("%PROC_DIR%\gluegen-rt-*-natives-windows-amd64-*.jar") do (
        powershell -NoProfile -Command "Expand-Archive -Path '%%j' -DestinationPath '%SKETCH_DIR%\build\natives' -Force" 2>nul
    )
    for %%j in ("%PROC_DIR%\jogl-all-*-natives-windows-amd64-*.jar") do (
        powershell -NoProfile -Command "Expand-Archive -Path '%%j' -DestinationPath '%SKETCH_DIR%\build\natives' -Force" 2>nul
    )
    for /R "%SKETCH_DIR%\build\natives" %%d in (*.dll) do (
        if not "%%~dpd"=="%SKETCH_DIR%\build\natives\" move /Y "%%d" "%SKETCH_DIR%\build\natives\" 2>nul
    )
    dir /B "%SKETCH_DIR%\build\natives\*.dll" 2>nul
)
echo [4/4a] Done.

echo [4/4] Compiling with javac...
set CP=
for %%j in (%SKETCH_DIR%\build_tools\*.jar) do set CP=!CP!;%%j
for /R "%SKETCH_DIR%\libraries" %%j in (*.jar) do set CP=!CP!;%%j
set CP=!CP!;%SKETCH_DIR%\code\LSLLink.jar
if not exist "%SKETCH_DIR%\build\classes" mkdir "%SKETCH_DIR%\build\classes" 2>nul
"%JAVAC%" -encoding UTF-8 --module-path "%SKETCH_DIR%\javafx\lib" --add-modules javafx.controls,javafx.media,javafx.swing -d "%SKETCH_DIR%\build\classes" -cp "!CP!" "%JAVA_FILE%"
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo Compilation FAILED!
    pause
    exit /b 1
)
echo [4/4] Done.

echo.
echo ============================================
echo  BUILD SUCCESSFUL!
echo  Run with: run.bat
echo ============================================
pause
exit /b 0

:compile_fail
echo.
echo ERROR: Preprocessing failed - cannot find sketch imports.
echo.
pause
